[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @pk-candle/server build"]

[start]
cmd = "pnpm --filter @pk-candle/server start"
